# Collaboration avec Kinnie

import os
from glob import glob
import pandas as pd

configfile: "config.yaml"

GENOMES = [os.path.basename(genome) for genome in glob("data/genomes/GC*")]

TIMEOUT=["timeout"]

FORMATS=["_gff.tsv",".faa"]

# Règle pour vérifier si tous les fichiers de sortie existent
rule all:
    input:
        expand("results/genomes/{genome}/PGCfinder", genome=GENOMES),
        expand("data/genomes_unzip/{genome}/{genome}_protein_gff.tsv", genome=GENOMES, format=FORMATS),
        "results/lists/list_organisms_merged.csv"

# Règle pour décompresser les génomes
rule unzip_genomes:
    input: "data/genomes/{genome}/{genome}_protein{format}.gz"
    output: "data/genomes_unzip/{genome}/{genome}_protein{format}"
    shell: "gunzip -c {input} > {output}"

# Rule to launch PGCfinder with the correct parameters on all the genomes
rule PGCfinder:
    input:
        "data/genomes_unzip/{genome}/{genome}_protein.faa"
    output:
        directory("results/genomes/{genome}/PGCfinder")
    shell:
        """
        mkdir -p {output}
        macsyfinder --db-type ordered_replicon --sequence-db {input} --timeout {TIMEOUT} --models PGCFinder all -o results/genomes/{wildcards.genome}/PGCfinder/
        """

# Rule to create a file with all the names of the genomes that have been given previously with all the taxonomy and useful informations
rule dir_finder:
    input:
        "results/genomes"
    output:
        "results/lists/list_organisms_merged.csv"
    shell:
        """
        find {input} -maxdepth 1 -mindepth 1 -type d -exec basename {{}} \;> results/lists/list_organisms.csv
        python3 scripts/merge_csv.py
        python3 scripts/merge_list_organism.py
        """
