#collaboration avec Kinnie

import os
from glob import glob
import pandas as pd

configfile: "config.yaml"

GENOMES = [os.path.basename(genome) for genome in glob("data/genomes/GCA*")]

# Règle pour vérifier si tous les fichiers de sortie existent
rule all:
    input:
        expand("data/genomes_unzip/{genome}/{genome}_protein.faa", genome=GENOMES)

# Règle pour décompresser les génomes
rule unzip_genomes:
    input:  "data/genomes/{genome}/{genome}_protein.faa.gz"
    output: "data/genomes_unzip/{genome}/{genome}_protein.faa"
    shell:  "cp {input} {output}.gz && gunzip {output}.gz"
